import numpy as np
from manim import *
from stitcher_scene import StitcherScene


class MatrixAlgebra(StitcherScene):
    def construct_scene(self):
        with self.voiceover("Now it's time to try to derive a formula for the hat matrix.") as tracker:
            ...
        with self.voiceover("As it happens, I want to give a series of logical derivations that end with the hat matrix, but") as tracker:
            ...
        with self.voiceover("most of the 'derivations' end up being more like, here I just pulled the hat matrix out of the blue, now here's the proof as to why it's correct.") as tracker:
            ...
        with self.voiceover("So first thing, we want every column of X to be unchanged when multiplying by H.") as tracker:
            ...
        with self.voiceover("This is equivalent to saying that H X equals X.") as tracker:
            ...
        with self.voiceover("The matrix X is left alone if and only if every column of it is left alone.") as tracker:
            ...
        with self.voiceover("We also know that H times anything orthogonal to all the columns of X should be 0.") as tracker:
            ...
        with self.voiceover("Note that X transpose times anything orthogonal to all the columns of X is zero.") as tracker:
            ...
        with self.voiceover("So if H is equal to something times X transpose, it satisfies this second property that ") as tracker:
            ...
        