import numpy as np
from manim import *
from MF_Tools import *

#Some useful helper methods
def as_row(vec):
    return vec.reshape(1,-1)
def as_col(vec):
    return vec.reshape(-1,1)

def round_sig(x, sig=4):
    x = np.asarray(x)
    
    # Handle zeros separately to avoid log10 issues
    zero_mask = (x == 0)
    
    # Compute scale factor
    mags = np.floor(np.log10(np.abs(x)), where=~zero_mask, out=np.zeros_like(x))
    factor = np.power(10, sig - 1 - mags)
    
    # Round and rescale
    result = np.round(x * factor) / factor
    
    # Restore zeros
    result[zero_mask] = 0
    return result

# Turns a numpy tensor into TeX which is nice for displaying.
# Generated by ChatGPT, modified by Noah
def numpy_to_latex(
    arr: np.ndarray,
    sigfigs: int = 4,
    max_rows: int = -1, # -1 automatically calculates
    max_cols: int = -1, # -1 automatically calculates
    tail_rows: int = 2,
    tail_cols: int = 2,
    make_table: bool = False,
    colnames: list[str] = []
) -> str:
    if not isinstance(arr, np.ndarray):
        raise TypeError("Input must be a numpy.ndarray")

    if arr.ndim >= 3:
        raise ValueError("Array must be 1D or 2D")

    # Treat 1D arrays as column vectors
    if arr.ndim == 1:
        arr = as_col(arr)

    n_rows, n_cols = arr.shape
    
    # If automatically calculating max_rows or max_cols, do so here
    def display_size(
        n,
        full_threshold=8,
        max_display=14,
        scale=0.03):
        if n <= full_threshold:
            return n
        return min(max_display, int(full_threshold + scale * (n - full_threshold)))
    
    if max_rows == -1:
        max_rows = display_size(n_rows)
    if max_cols == -1:
        max_cols = display_size(n_cols)

    if tail_rows < 0 or tail_cols < 0:
        raise ValueError("tail_rows and tail_cols must be nonnegative")

    def format_entry(x):
        try:
            x = float(x)
            return f"{x:.{sigfigs}g}"
        except (ValueError, TypeError):
            return str(x)

    def indices(n, max_n, tail_n):
        if n <= max_n:
            return list(range(n)), False

        if tail_n + 1 >= max_n:
            raise ValueError("tail_n is too large relative to max_n")

        head_n = max_n - tail_n - 1
        idx = list(range(head_n)) + list(range(n - tail_n, n))
        return idx, True

    row_idx, row_trunc = indices(n_rows, max_rows, tail_rows)
    col_idx, col_trunc = indices(n_cols, max_cols, tail_cols)

    if colnames:
        rows = [" & ".join(colnames) + "\n"]
    else:
        rows = []

    for i in row_idx:
        entries = []
        for j in col_idx:
            entries.append(format_entry(arr[i, j]))

        if col_trunc:
            # Insert horizontal ellipsis before the tail columns
            insert_at = len(entries) - tail_cols
            entries.insert(insert_at, r"\ldots")

        rows.append(" & ".join(entries))

    if row_trunc:
        ellipsis_row = []
        displayed_cols = len(col_idx) + (1 if col_trunc else 0)
        if make_table:
            ellipsis_row = [r"$\vdots$"] * displayed_cols
        else:
            ellipsis_row = [r"\vdots"] * displayed_cols

        if col_trunc:
            ellipsis_col = len(ellipsis_row) - tail_cols - 1
            ellipsis_row[ellipsis_col] = r"$\ddots$" if make_table else r"\ddots" 

        # Insert ellipsis row before the tail rows
        insert_at = len(rows) - tail_rows
        rows.insert(insert_at, " & ".join(ellipsis_row))

    if make_table:
        body = " \\\\\n\\hline\n    ".join(rows)
        body = f"\\hline\n{body} \\\\\n\\hline\n"
    else:
        body = " \\\\\n    ".join(rows)

    # Check that every column has the same number of "&" because otherwise LaTeX will complain
    if True:
        expected_cols = None
        for r in rows:
            count = r.count("&")
            if expected_cols is None:
                expected_cols = count
            elif count != expected_cols:
                raise RuntimeError("Inconsistent column count in LaTeX matrix")

    
    if make_table:
        header_text = "|" + " c |" * max_cols
        return (
            f"\\begin{{tabular}}{{ {header_text} }}\n"
            f"    {body}\n"
            "\\end{tabular}"
        )
    else:
        return (
            "\\begin{bmatrix}\n"
            f"    {body}\n"
            "\\end{bmatrix}"
        )

def bhat_extremes(axes, X, base, direction):
    """Finds how far bhat = base + t*direction can go, in either direction,
    before X @ bhat leaves axes' plotted range (x_range/y_range/z_range) in
    any dimension.

    Returns (bhat_min, bhat_max): the two bhat vectors at the most negative
    and most positive feasible t.
    """
    base = np.array(base, dtype=float)
    direction = np.array(direction, dtype=float)
    base_yhat = X @ base
    step_yhat = X @ direction

    t_min, t_max = -np.inf, np.inf
    for axis_range, base_i, step_i in zip(
        (axes.x_range, axes.y_range, axes.z_range), base_yhat, step_yhat
    ):
        lo, hi = axis_range[0], axis_range[1]
        if step_i > 0:
            t_min = max(t_min, (lo - base_i) / step_i)
            t_max = min(t_max, (hi - base_i) / step_i)
        elif step_i < 0:
            t_min = max(t_min, (hi - base_i) / step_i)
            t_max = min(t_max, (lo - base_i) / step_i)
        # step_i == 0: this dimension doesn't constrain t

    return base + t_min * direction, base + t_max * direction

class ArrayValueTracker(ValueTracker):
    """A ValueTracker that holds a numpy array of any shape instead of a single
    scalar, so it can be animated the same way with `.animate.set_value(new_array)`.

    Mobject (which ValueTracker subclasses) stores its state as `self.points`,
    an (N, 3) array of render points. We pack the tracked array's values into
    that same (N, 3) buffer (flattening/reshaping as needed) and remember the
    original shape so get_value() can hand back an array shaped like the input.
    """

    def __init__(self, array=None, **kwargs):
        Mobject.__init__(self, **kwargs)
        array = np.zeros(1) if array is None else np.array(array, dtype=float)
        self.array_shape = array.shape
        n_rows = max(1, int(np.ceil(array.size / 3)))
        self.points = np.zeros((n_rows, 3))
        self.set_value(array)

    def get_value(self):
        flat = self.points.flatten()[: np.prod(self.array_shape, dtype=int)]
        return flat.reshape(self.array_shape)

    def set_value(self, array):
        array = np.array(array, dtype=float)
        flat = self.points.flatten()
        flat[: array.size] = array.flatten()
        self.points = flat.reshape(self.points.shape)
        return self

    def increment_value(self, d_array):
        self.set_value(self.get_value() + np.array(d_array))
        return self

class FlashOn(Succession):
    """
    Fades a mobject in, holds it, then fades it out.

    run_time can be:
      - a single number  → split evenly into (in, hold, out)
      - a 3-tuple        → (fade_in_time, hold_time, fade_out_time)
    """
    def __init__(
        self,
        mobject,
        run_time=3.0,
        fade_in=FadeIn,
        fade_out=FadeOut,
        **kwargs,
    ):
        if isinstance(run_time, (tuple, list)):
            t_in, t_hold, t_out = run_time
        else:
            t_in = t_hold = t_out = run_time / 3

        super().__init__(
            fade_in(mobject, run_time=t_in),
            Wait(t_hold),
            fade_out(mobject, run_time=t_out),
            **kwargs,
        )

# Created by GniLudio
class Combine(AnimationGroup):
    def _setup_scene(self, scene: Scene) -> None:
        super()._setup_scene(scene)
        self._scene = scene
        self._initial_mobjects = {
            mob: mob.copy()
            for mob in self.group
            if type(mob).interpolate_color != Mobject.interpolate_color
        }

    def interpolate(self, alpha: float) -> None:
        for mobject, initial_mobject in self._initial_mobjects.items():
            mobject.become(initial_mobject)
        for animation in self.animations:
            animation._setup_scene(self._scene)
            animation.begin()
            animation.interpolate(alpha)

class Testing3(ThreeDScene):
    def construct(self):
        sq = Cube(
            side_length=1,
            )

        self.add(
            sq,
        )

        self.wait()

        self.play(
            Combine(
                Rotate(
                    sq, angle=2*PI, axis=UP
                ),
                sq.animate.shift(RIGHT),
            ),
            run_time=2,
            rate_func=smooth,
        )

        self.wait()

# Generated by ChatGPT
# TODO: More robust strategies for dealing with fraction bars and pipes, etc.
def extract_table_grid(tex):
    glyphs = tex[0]

    vertical_lines = []
    horizontal_lines = []
    content = []

    # --- Step 1: classify glyphs ---
    for i, g in enumerate(glyphs):
        w, h = g.width, g.height

        if h > 5 * w:  # vertical line
            vertical_lines.append((i, g))
        elif w > 5 * h:  # horizontal line
            horizontal_lines.append((i, g))
        else:
            content.append((i, g))

    # print(f"{vertical_lines=}, {horizontal_lines=}, {content=}")

    # --- Step 2: get grid boundaries ---
    # Use centers of lines
    x_lines = sorted([g.get_center()[0] for _, g in vertical_lines])
    y_lines = sorted([g.get_center()[1] for _, g in horizontal_lines], reverse=True)

    # Deduplicate (important if LaTeX draws lines in segments)
    def dedup(vals, tol=1e-2):
        out = []
        for v in vals:
            if not any(abs(v - o) < tol for o in out):
                out.append(v)
        return sorted(out)

    x_lines = dedup(x_lines)
    y_lines = dedup(y_lines)[::-1]  # top → bottom

    # --- Step 3: build cells ---
    grid = {}

    for idx, g in content:
        x, y, _z = g.get_center()

        # find column: between vertical lines
        col = None
        for j in range(len(x_lines) - 1):
            if x_lines[j] < x < x_lines[j + 1]:
                col = j
                break

        # find row: between horizontal lines
        row = None
        for i in range(len(y_lines) - 1):
            if y_lines[i] > y > y_lines[i + 1]:
                row = i
                break

        if row is not None and col is not None:
            grid.setdefault((row, col), []).append(idx)
        else:
            pass
            # print((row, col))

    return grid

def get_matching_cell_map(table1, table2):
    table1_grid = extract_table_grid(table1)
    table2_grid = extract_table_grid(table2)

    glyph_map = []
    maps = table1_grid.keys() | table2_grid.keys()
    for coords in maps:
        start_indices = table1_grid[coords] if coords in table1_grid else []
        end_indices = table2_grid[coords] if coords in table2_grid else []
        glyph_map.append((start_indices, end_indices))

    return glyph_map

def TransformMatchingCells(table1, table2):
    return TransformByGlyphMap(table1, table2, *get_matching_cell_map(table1, table2))

def get_matrix_element_indices(tex, row: int, col: int) -> list[int]:
    """
    Return the glyph indices for the element at (row, col), both 0-indexed,
    of a MathTex (or MathTexPart slice like MathTex(...)[2]) containing only
    a single matrix environment.

    Indices are into the glyph container: tex[0] for a full MathTex, or tex
    itself for a MathTexPart (e.g. the result of MathTex(...)[n]).

    Works by re-rendering the same matrix with row_sep=100pt so that row
    gaps are enormous and detection is trivially reliable. The returned indices
    are valid for the original tex because same LaTeX → same glyph count and
    rendering order; only y-positions differ.
    """
    import re

    # MathTex stores tex_strings as a list — when substrings_to_isolate is active
    # (e.g. ColoredMathTex) the list is the original string split at every isolated
    # symbol.  Joining reconstructs the full LaTeX.  MathTexPart has tex_string (str).
    if hasattr(tex, 'tex_strings'):
        latex = "".join(tex.tex_strings)
    else:
        latex = tex.tex_string

    # --- 1. Parse matrix dimensions from LaTeX ---
    # Use a capturing regex so that surrounding content (e.g. "$...$" from Tex objects)
    # is ignored — only the body between \begin{env} and \end{env} is extracted.
    env_match = re.search(r'\\begin\{([^}]+)\}(.*?)\\end\{[^}]+\}', latex, re.DOTALL)
    if not env_match:
        raise ValueError("No matrix environment found in LaTeX")
    bracket = env_match.group(1)
    inner = env_match.group(2)
    # \\[optional_length] is the row separator; strip the optional part when splitting
    row_strs = [r.strip() for r in re.split(r'\\\\(?:\[[^\]]*\])?', inner)]
    n_rows = len(row_strs)
    n_cols = max(len(r.split('&')) for r in row_strs)

    if not (0 <= row < n_rows):
        raise IndexError(f"row {row} out of range for {n_rows}-row matrix")
    if not (0 <= col < n_cols):
        raise IndexError(f"col {col} out of range for {n_cols}-col matrix")

    # --- 2. Re-render with huge row_sep so geometric detection is reliable ---
    # Note: very tall brackets may render as multiple stacked glyph pieces (more glyphs
    # in temp than in original), so we track POSITION in the non-bracket content list
    # rather than raw glyph indices, then remap to the original at the end.
    temp_body = " \\\\[100pt]\n".join(row_strs)
    temp = MathTex(f"\\begin{{{bracket}}}{temp_body}\\end{{{bracket}}}")
    temp_glyphs = temp[0]

    # --- 3. Identify bracket glyphs in temp (h/w > 3, very reliable at 100pt spacing) ---
    temp_bracket_set = {
        i for i, g in enumerate(temp_glyphs)
        if g.width > 0 and g.height / g.width > 3
    }
    # content_list: (position_in_content_list, glyph_obj) — NOT temp glyph indices
    content = list(enumerate(
        g for i, g in enumerate(temp_glyphs) if i not in temp_bracket_set
    ))

    # --- 4. Split content into matrix rows via largest y-gaps ---
    content_by_y = sorted(content, key=lambda x: -x[1].get_center()[1])
    ys = [g.get_center()[1] for _, g in content_by_y]

    if n_rows > 1:
        gaps = sorted(
            ((ys[k] - ys[k + 1], k) for k in range(len(ys) - 1)),
            reverse=True
        )
        split_pts = sorted(k for _, k in gaps[:n_rows - 1])
        rows_content: list[list] = []
        prev = 0
        for sp in split_pts:
            rows_content.append(content_by_y[prev:sp + 1])
            prev = sp + 1
        rows_content.append(content_by_y[prev:])
    else:
        rows_content = [content_by_y]

    # Sort each row's glyphs left-to-right
    for r in rows_content:
        r.sort(key=lambda x: x[1].get_center()[0])

    # --- 5. Split target row into columns via largest x-gaps ---
    target = rows_content[row]

    if n_cols == 1 or len(target) <= 1:
        target_positions = [k for k, _ in target]
    else:
        xs = [g.get_center()[0] for _, g in target]
        x_gaps = sorted(
            ((xs[j + 1] - xs[j], j) for j in range(len(xs) - 1)),
            reverse=True
        )
        split_pts_x = sorted(j for _, j in x_gaps[:n_cols - 1])

        col_groups: list[list] = []
        prev = 0
        for sp in split_pts_x:
            col_groups.append(target[prev:sp + 1])
            prev = sp + 1
        col_groups.append(target[prev:])
        target_positions = [k for k, _ in col_groups[col]]

    # --- 6. Map content-list positions back to original glyph indices ---
    orig_glyphs = tex[0] if hasattr(tex, 'tex_strings') else tex
    orig_bracket_set = {
        i for i, g in enumerate(orig_glyphs)
        if g.width > 0 and g.height / g.width > 3
    }
    orig_content_by_pos = [i for i in range(len(orig_glyphs)) if i not in orig_bracket_set]

    return [orig_content_by_pos[k] for k in target_positions]
