import numpy as np
from manim import *

#Some useful helper methods
def as_row(vec):
    return vec.reshape(1,-1)
def as_col(vec):
    return vec.reshape(-1,1)

def round_sig(x, sig=4):
    x = np.asarray(x)
    
    # Handle zeros separately to avoid log10 issues
    zero_mask = (x == 0)
    
    # Compute scale factor
    mags = np.floor(np.log10(np.abs(x)), where=~zero_mask, out=np.zeros_like(x))
    factor = np.power(10, sig - 1 - mags)
    
    # Round and rescale
    result = np.round(x * factor) / factor
    
    # Restore zeros
    result[zero_mask] = 0
    return result

# Turns a numpy tensor into TeX which is nice for displaying.
# Generated by ChatGPT, modified by Noah
def numpy_to_latex(
    arr: np.ndarray,
    sigfigs: int = 4,
    max_rows: int = -1, # -1 automatically calculates
    max_cols: int = -1, # -1 automatically calculates
    tail_rows: int = 2,
    tail_cols: int = 2,
    make_table: bool = False,
    colnames: list[str] = []
) -> str:
    if not isinstance(arr, np.ndarray):
        raise TypeError("Input must be a numpy.ndarray")

    if arr.ndim >= 3:
        raise ValueError("Array must be 1D or 2D")

    # Treat 1D arrays as column vectors
    if arr.ndim == 1:
        arr = as_col(arr)

    n_rows, n_cols = arr.shape
    
    # If automatically calculating max_rows or max_cols, do so here
    def display_size(
        n,
        full_threshold=8,
        max_display=14,
        scale=0.03):
        if n <= full_threshold:
            return n
        return min(max_display, int(full_threshold + scale * (n - full_threshold)))
    
    if max_rows == -1:
        max_rows = display_size(n_rows)
    if max_cols == -1:
        max_cols = display_size(n_cols)

    if tail_rows < 0 or tail_cols < 0:
        raise ValueError("tail_rows and tail_cols must be nonnegative")

    def format_entry(x):
        try:
            x = float(x)
            return f"{x:.{sigfigs}g}"
        except (ValueError, TypeError):
            return str(x)

    def indices(n, max_n, tail_n):
        if n <= max_n:
            return list(range(n)), False

        if tail_n + 1 >= max_n:
            raise ValueError("tail_n is too large relative to max_n")

        head_n = max_n - tail_n - 1
        idx = list(range(head_n)) + list(range(n - tail_n, n))
        return idx, True

    row_idx, row_trunc = indices(n_rows, max_rows, tail_rows)
    col_idx, col_trunc = indices(n_cols, max_cols, tail_cols)

    if colnames:
        rows = [" & ".join(colnames) + "\n"]
    else:
        rows = []

    for i in row_idx:
        entries = []
        for j in col_idx:
            entries.append(format_entry(arr[i, j]))

        if col_trunc:
            # Insert horizontal ellipsis before the tail columns
            insert_at = len(entries) - tail_cols
            entries.insert(insert_at, r"\ldots")

        rows.append(" & ".join(entries))

    if row_trunc:
        ellipsis_row = []
        displayed_cols = len(col_idx) + (1 if col_trunc else 0)
        if make_table:
            ellipsis_row = [r"$\vdots$"] * displayed_cols
        else:
            ellipsis_row = [r"\vdots"] * displayed_cols

        if col_trunc:
            ellipsis_col = len(ellipsis_row) - tail_cols - 1
            ellipsis_row[ellipsis_col] = r"$\ddots$" if make_table else r"\ddots" 

        # Insert ellipsis row before the tail rows
        insert_at = len(rows) - tail_rows
        rows.insert(insert_at, " & ".join(ellipsis_row))

    if make_table:
        body = " \\\\\n\\hline\n    ".join(rows)
        body = f"\\hline\n{body} \\\\\n\\hline\n"
    else:
        body = " \\\\\n    ".join(rows)

    # Check that every column has the same number of "&" because otherwise LaTeX will complain
    if True:
        expected_cols = None
        for r in rows:
            count = r.count("&")
            if expected_cols is None:
                expected_cols = count
            elif count != expected_cols:
                raise RuntimeError("Inconsistent column count in LaTeX matrix")

    
    if make_table:
        header_text = "|" + " c |" * max_cols
        return (
            f"\\begin{{tabular}}{{ {header_text} }}\n"
            f"    {body}\n"
            "\\end{tabular}"
        )
    else:
        return (
            "\\begin{bmatrix}\n"
            f"    {body}\n"
            "\\end{bmatrix}"
        )

class ArrayValueTracker(ValueTracker):
    """A ValueTracker that holds a numpy array of any shape instead of a single
    scalar, so it can be animated the same way with `.animate.set_value(new_array)`.

    Mobject (which ValueTracker subclasses) stores its state as `self.points`,
    an (N, 3) array of render points. We pack the tracked array's values into
    that same (N, 3) buffer (flattening/reshaping as needed) and remember the
    original shape so get_value() can hand back an array shaped like the input.
    """

    def __init__(self, array=None, **kwargs):
        Mobject.__init__(self, **kwargs)
        array = np.zeros(1) if array is None else np.array(array, dtype=float)
        self.array_shape = array.shape
        n_rows = max(1, int(np.ceil(array.size / 3)))
        self.points = np.zeros((n_rows, 3))
        self.set_value(array)

    def get_value(self):
        flat = self.points.flatten()[: np.prod(self.array_shape, dtype=int)]
        return flat.reshape(self.array_shape)

    def set_value(self, array):
        array = np.array(array, dtype=float)
        flat = self.points.flatten()
        flat[: array.size] = array.flatten()
        self.points = flat.reshape(self.points.shape)
        return self

    def increment_value(self, d_array):
        self.set_value(self.get_value() + np.array(d_array))
        return self
