import numpy as np
from manim import *
from MF_Tools import *

#Some useful helper methods
def as_row(vec):
    return vec.reshape(1,-1)
def as_col(vec):
    return vec.reshape(-1,1)

def round_sig(x, sig=4):
    x = np.asarray(x)
    
    # Handle zeros separately to avoid log10 issues
    zero_mask = (x == 0)
    
    # Compute scale factor
    mags = np.floor(np.log10(np.abs(x)), where=~zero_mask, out=np.zeros_like(x))
    factor = np.power(10, sig - 1 - mags)
    
    # Round and rescale
    result = np.round(x * factor) / factor
    
    # Restore zeros
    result[zero_mask] = 0
    return result

# Turns a numpy tensor into TeX which is nice for displaying.
# Generated by ChatGPT, modified by Noah
def numpy_to_latex(
    arr: np.ndarray,
    sigfigs: int = 4,
    max_rows: int = -1, # -1 automatically calculates
    max_cols: int = -1, # -1 automatically calculates
    tail_rows: int = 2,
    tail_cols: int = 2,
    make_table: bool = False,
    colnames: list[str] = []
) -> str:
    if not isinstance(arr, np.ndarray):
        raise TypeError("Input must be a numpy.ndarray")

    if arr.ndim >= 3:
        raise ValueError("Array must be 1D or 2D")

    # Treat 1D arrays as column vectors
    if arr.ndim == 1:
        arr = as_col(arr)

    n_rows, n_cols = arr.shape
    
    # If automatically calculating max_rows or max_cols, do so here
    def display_size(
        n,
        full_threshold=8,
        max_display=14,
        scale=0.03):
        if n <= full_threshold:
            return n
        return min(max_display, int(full_threshold + scale * (n - full_threshold)))
    
    if max_rows == -1:
        max_rows = display_size(n_rows)
    if max_cols == -1:
        max_cols = display_size(n_cols)

    if tail_rows < 0 or tail_cols < 0:
        raise ValueError("tail_rows and tail_cols must be nonnegative")

    def format_entry(x):
        try:
            x = float(x)
            return f"{x:.{sigfigs}g}"
        except (ValueError, TypeError):
            return str(x)

    def indices(n, max_n, tail_n):
        if n <= max_n:
            return list(range(n)), False

        if tail_n + 1 >= max_n:
            raise ValueError("tail_n is too large relative to max_n")

        head_n = max_n - tail_n - 1
        idx = list(range(head_n)) + list(range(n - tail_n, n))
        return idx, True

    row_idx, row_trunc = indices(n_rows, max_rows, tail_rows)
    col_idx, col_trunc = indices(n_cols, max_cols, tail_cols)

    if colnames:
        rows = [" & ".join(colnames) + "\n"]
    else:
        rows = []

    for i in row_idx:
        entries = []
        for j in col_idx:
            entries.append(format_entry(arr[i, j]))

        if col_trunc:
            # Insert horizontal ellipsis before the tail columns
            insert_at = len(entries) - tail_cols
            entries.insert(insert_at, r"\ldots")

        rows.append(" & ".join(entries))

    if row_trunc:
        ellipsis_row = []
        displayed_cols = len(col_idx) + (1 if col_trunc else 0)
        if make_table:
            ellipsis_row = [r"$\vdots$"] * displayed_cols
        else:
            ellipsis_row = [r"\vdots"] * displayed_cols

        if col_trunc:
            ellipsis_col = len(ellipsis_row) - tail_cols - 1
            ellipsis_row[ellipsis_col] = r"$\ddots$" if make_table else r"\ddots" 

        # Insert ellipsis row before the tail rows
        insert_at = len(rows) - tail_rows
        rows.insert(insert_at, " & ".join(ellipsis_row))

    if make_table:
        body = " \\\\\n\\hline\n    ".join(rows)
        body = f"\\hline\n{body} \\\\\n\\hline\n"
    else:
        body = " \\\\\n    ".join(rows)

    # Check that every column has the same number of "&" because otherwise LaTeX will complain
    if True:
        expected_cols = None
        for r in rows:
            count = r.count("&")
            if expected_cols is None:
                expected_cols = count
            elif count != expected_cols:
                raise RuntimeError("Inconsistent column count in LaTeX matrix")

    
    if make_table:
        header_text = "|" + " c |" * max_cols
        return (
            f"\\begin{{tabular}}{{ {header_text} }}\n"
            f"    {body}\n"
            "\\end{tabular}"
        )
    else:
        return (
            "\\begin{bmatrix}\n"
            f"    {body}\n"
            "\\end{bmatrix}"
        )

def bhat_extremes(axes, X, base, direction):
    """Finds how far bhat = base + t*direction can go, in either direction,
    before X @ bhat leaves axes' plotted range (x_range/y_range/z_range) in
    any dimension.

    Returns (bhat_min, bhat_max): the two bhat vectors at the most negative
    and most positive feasible t.
    """
    base = np.array(base, dtype=float)
    direction = np.array(direction, dtype=float)
    base_yhat = X @ base
    step_yhat = X @ direction

    t_min, t_max = -np.inf, np.inf
    for axis_range, base_i, step_i in zip(
        (axes.x_range, axes.y_range, axes.z_range), base_yhat, step_yhat
    ):
        lo, hi = axis_range[0], axis_range[1]
        if step_i > 0:
            t_min = max(t_min, (lo - base_i) / step_i)
            t_max = min(t_max, (hi - base_i) / step_i)
        elif step_i < 0:
            t_min = max(t_min, (hi - base_i) / step_i)
            t_max = min(t_max, (lo - base_i) / step_i)
        # step_i == 0: this dimension doesn't constrain t

    return base + t_min * direction, base + t_max * direction

class ArrayValueTracker(ValueTracker):
    """A ValueTracker that holds a numpy array of any shape instead of a single
    scalar, so it can be animated the same way with `.animate.set_value(new_array)`.

    Mobject (which ValueTracker subclasses) stores its state as `self.points`,
    an (N, 3) array of render points. We pack the tracked array's values into
    that same (N, 3) buffer (flattening/reshaping as needed) and remember the
    original shape so get_value() can hand back an array shaped like the input.
    """

    def __init__(self, array=None, **kwargs):
        Mobject.__init__(self, **kwargs)
        array = np.zeros(1) if array is None else np.array(array, dtype=float)
        self.array_shape = array.shape
        n_rows = max(1, int(np.ceil(array.size / 3)))
        self.points = np.zeros((n_rows, 3))
        self.set_value(array)

    def get_value(self):
        flat = self.points.flatten()[: np.prod(self.array_shape, dtype=int)]
        return flat.reshape(self.array_shape)

    def set_value(self, array):
        array = np.array(array, dtype=float)
        flat = self.points.flatten()
        flat[: array.size] = array.flatten()
        self.points = flat.reshape(self.points.shape)
        return self

    def increment_value(self, d_array):
        self.set_value(self.get_value() + np.array(d_array))
        return self

class FlashOn(Succession):
    """
    Fades a mobject in, holds it, then fades it out.

    run_time can be:
      - a single number  → split evenly into (in, hold, out)
      - a 3-tuple        → (fade_in_time, hold_time, fade_out_time)
    """
    def __init__(
        self,
        mobject,
        run_time=3.0,
        fade_in=FadeIn,
        fade_out=FadeOut,
        **kwargs,
    ):
        if isinstance(run_time, (tuple, list)):
            t_in, t_hold, t_out = run_time
        else:
            t_in = t_hold = t_out = run_time / 3

        super().__init__(
            fade_in(mobject, run_time=t_in),
            Wait(t_hold),
            fade_out(mobject, run_time=t_out),
            **kwargs,
        )

# Created by GniLudio
class Combine(AnimationGroup):
    def _setup_scene(self, scene: Scene) -> None:
        super()._setup_scene(scene)
        self._scene = scene
        self._initial_mobjects = {
            mob: mob.copy()
            for mob in self.group
            if type(mob).interpolate_color != Mobject.interpolate_color
        }

    def interpolate(self, alpha: float) -> None:
        for mobject, initial_mobject in self._initial_mobjects.items():
            mobject.become(initial_mobject)
        for animation in self.animations:
            animation._setup_scene(self._scene)
            animation.begin()
            animation.interpolate(alpha)

class Testing3(ThreeDScene):
    def construct(self):
        sq = Cube(
            side_length=1,
            )

        self.add(
            sq,
        )

        self.wait()

        self.play(
            Combine(
                Rotate(
                    sq, angle=2*PI, axis=UP
                ),
                sq.animate.shift(RIGHT),
            ),
            run_time=2,
            rate_func=smooth,
        )

        self.wait()

# Generated by ChatGPT
# TODO: More robust strategies for dealing with fraction bars and pipes, etc.
def extract_table_grid(tex):
    glyphs = tex[0]

    vertical_lines = []
    horizontal_lines = []
    content = []

    # --- Step 1: classify glyphs ---
    for i, g in enumerate(glyphs):
        w, h = g.width, g.height

        if h > 5 * w:  # vertical line
            vertical_lines.append((i, g))
        elif w > 5 * h:  # horizontal line
            horizontal_lines.append((i, g))
        else:
            content.append((i, g))

    # print(f"{vertical_lines=}, {horizontal_lines=}, {content=}")

    # --- Step 2: get grid boundaries ---
    # Use centers of lines
    x_lines = sorted([g.get_center()[0] for _, g in vertical_lines])
    y_lines = sorted([g.get_center()[1] for _, g in horizontal_lines], reverse=True)

    # Deduplicate (important if LaTeX draws lines in segments)
    def dedup(vals, tol=1e-2):
        out = []
        for v in vals:
            if not any(abs(v - o) < tol for o in out):
                out.append(v)
        return sorted(out)

    x_lines = dedup(x_lines)
    y_lines = dedup(y_lines)[::-1]  # top → bottom

    # --- Step 3: build cells ---
    grid = {}

    for idx, g in content:
        x, y, _z = g.get_center()

        # find column: between vertical lines
        col = None
        for j in range(len(x_lines) - 1):
            if x_lines[j] < x < x_lines[j + 1]:
                col = j
                break

        # find row: between horizontal lines
        row = None
        for i in range(len(y_lines) - 1):
            if y_lines[i] > y > y_lines[i + 1]:
                row = i
                break

        if row is not None and col is not None:
            grid.setdefault((row, col), []).append(idx)
        else:
            pass
            # print((row, col))

    return grid

def get_matching_cell_map(table1, table2):
    table1_grid = extract_table_grid(table1)
    table2_grid = extract_table_grid(table2)

    glyph_map = []
    maps = table1_grid.keys() | table2_grid.keys()
    for coords in maps:
        start_indices = table1_grid[coords] if coords in table1_grid else []
        end_indices = table2_grid[coords] if coords in table2_grid else []
        glyph_map.append((start_indices, end_indices))

    return glyph_map

def TransformMatchingCells(table1, table2):
    return TransformByGlyphMap(table1, table2, *get_matching_cell_map(table1, table2))

def get_matrix_grid_indices(tex) -> list[list[list[int]]]:
    """
    Return the glyph indices for *every* element of a single matrix environment
    in `tex`, as a nested list: grid[row][col] is the list of glyph indices for
    the element at (row, col), both 0-indexed. A column vector is just the
    n_cols == 1 case, so grid[i][0] is the i-th entry.

    Indices are into the glyph container: tex[0] for a full MathTex, or tex
    itself for a MathTexPart (e.g. the result of MathTex(...)[n]).

    This is the all-elements generalization of get_matrix_element_indices: it
    does the (comparatively expensive) huge-row_sep re-render + geometric
    splitting ONCE for the whole matrix instead of once per element, so building
    a full multiplication animation is a single render rather than n*m of them.

    Works by re-rendering the same matrix with row_sep=100pt so that row gaps
    are enormous and detection is trivially reliable. The returned indices are
    valid for the original tex because same LaTeX → same glyph count and
    rendering order; only y-positions differ.
    """
    import re

    # MathTex stores tex_strings as a list — when substrings_to_isolate is active
    # (e.g. ColoredMathTex) the list is the original string split at every isolated
    # symbol.  Joining reconstructs the full LaTeX.  MathTexPart has tex_string (str).
    if hasattr(tex, 'tex_strings'):
        latex = "".join(tex.tex_strings)
    else:
        latex = tex.tex_string

    # --- 1. Parse matrix dimensions from LaTeX ---
    # Use a capturing regex so that surrounding content (e.g. "$...$" from Tex objects)
    # is ignored — only the body between \begin{env} and \end{env} is extracted.
    env_match = re.search(r'\\begin\{([^}]+)\}(.*?)\\end\{[^}]+\}', latex, re.DOTALL)
    if not env_match:
        raise ValueError("No matrix environment found in LaTeX")
    bracket = env_match.group(1)
    inner = env_match.group(2)
    # \\[optional_length] is the row separator; strip the optional part when splitting
    row_strs = [r.strip() for r in re.split(r'\\\\(?:\[[^\]]*\])?', inner)]
    n_rows = len(row_strs)
    n_cols = max(len(r.split('&')) for r in row_strs)

    # --- 2. Re-render with huge row_sep so geometric detection is reliable ---
    # Note: very tall brackets may render as multiple stacked glyph pieces (more glyphs
    # in temp than in original), so we track POSITION in the non-bracket content list
    # rather than raw glyph indices, then remap to the original at the end.
    temp_body = " \\\\[100pt]\n".join(row_strs)
    temp = MathTex(f"\\begin{{{bracket}}}{temp_body}\\end{{{bracket}}}")
    temp_glyphs = temp[0]

    # --- 3. Identify bracket glyphs in temp (h/w > 3, very reliable at 100pt spacing) ---
    temp_bracket_set = {
        i for i, g in enumerate(temp_glyphs)
        if g.width > 0 and g.height / g.width > 3
    }
    # content_list: (position_in_content_list, glyph_obj) — NOT temp glyph indices
    content = list(enumerate(
        g for i, g in enumerate(temp_glyphs) if i not in temp_bracket_set
    ))

    # --- 4. Split content into matrix rows via largest y-gaps ---
    content_by_y = sorted(content, key=lambda x: -x[1].get_center()[1])
    ys = [g.get_center()[1] for _, g in content_by_y]

    if n_rows > 1:
        gaps = sorted(
            ((ys[k] - ys[k + 1], k) for k in range(len(ys) - 1)),
            reverse=True
        )
        split_pts = sorted(k for _, k in gaps[:n_rows - 1])
        rows_content: list[list] = []
        prev = 0
        for sp in split_pts:
            rows_content.append(content_by_y[prev:sp + 1])
            prev = sp + 1
        rows_content.append(content_by_y[prev:])
    else:
        rows_content = [content_by_y]

    # Sort each row's glyphs left-to-right
    for r in rows_content:
        r.sort(key=lambda x: x[1].get_center()[0])

    # --- 5. Map content-list positions back to original glyph indices ---
    # The temp re-render is ONLY the matrix environment, but the original tex may
    # carry prefix/suffix glyphs around it (e.g. "X = [matrix]").  Restrict to the
    # glyphs strictly between the first and last bracket glyph so those extras are
    # excluded and the k-th temp entry lines up with the k-th original entry.
    orig_glyphs = tex[0] if hasattr(tex, 'tex_strings') else tex
    orig_bracket_indices = [
        i for i, g in enumerate(orig_glyphs)
        if g.width > 0 and g.height / g.width > 3
    ]
    if orig_bracket_indices:
        lo, hi = min(orig_bracket_indices), max(orig_bracket_indices)
        orig_bracket_set = set(orig_bracket_indices)
        orig_content_by_pos = [
            i for i in range(lo, hi + 1) if i not in orig_bracket_set
        ]
    else:
        # No brackets detected (unusual) — fall back to all glyphs, no prefix trim.
        orig_content_by_pos = list(range(len(orig_glyphs)))

    if len(orig_content_by_pos) != len(content):
        raise RuntimeError(
            f"glyph count mismatch: original matrix has {len(orig_content_by_pos)} "
            f"content glyphs but re-render has {len(content)}; cannot map indices"
        )

    # --- 6. Split every row into columns via largest x-gaps ---
    def split_row_into_cols(target):
        if n_cols == 1 or len(target) <= 1:
            groups = [target]
        else:
            xs = [g.get_center()[0] for _, g in target]
            x_gaps = sorted(
                ((xs[j + 1] - xs[j], j) for j in range(len(xs) - 1)),
                reverse=True
            )
            split_pts_x = sorted(j for _, j in x_gaps[:n_cols - 1])
            groups = []
            prev = 0
            for sp in split_pts_x:
                groups.append(target[prev:sp + 1])
                prev = sp + 1
            groups.append(target[prev:])
        # Guarantee exactly n_cols groups so grid[row][col] never IndexErrors,
        # even for a degenerate row with fewer glyphs than columns.
        while len(groups) < n_cols:
            groups.append([])
        return [[orig_content_by_pos[k] for k, _ in group] for group in groups]

    return [split_row_into_cols(row) for row in rows_content]


def get_matrix_element_indices(tex, row: int, col: int) -> list[int]:
    """
    Return the glyph indices for the element at (row, col), both 0-indexed, of a
    MathTex (or MathTexPart slice) containing a single matrix environment.

    Thin wrapper around get_matrix_grid_indices; prefer that directly when you
    need more than one element, since this re-renders the matrix on every call.
    """
    grid = get_matrix_grid_indices(tex)
    if not (0 <= row < len(grid)):
        raise IndexError(f"row {row} out of range for {len(grid)}-row matrix")
    if not (0 <= col < len(grid[row])):
        raise IndexError(f"col {col} out of range for {len(grid[row])}-col matrix")
    return grid[row][col]


def _tex_glyphs(tex):
    """The flat glyph container of a MathTex (its tex[0]) or of a MathTexPart
    slice like MathTex(...)[1] (the slice itself, whose submobjects are glyphs).
    Lets the matrix helpers accept either a full MathTex or an isolated part.
    """
    return tex[0] if hasattr(tex, 'tex_strings') else tex


def _matrix_entry_strings(tex) -> list[list[str]]:
    """Parse the LaTeX of a single matrix environment into a 2D list of the
    per-cell source strings (e.g. "1.5", "-2"), matching the layout used by
    get_matrix_grid_indices. These are reused verbatim when building the product
    expression, so each cell renders to the same glyph count it had in `tex`.
    """
    import re

    if hasattr(tex, 'tex_strings'):
        latex = "".join(tex.tex_strings)
    else:
        latex = tex.tex_string

    env_match = re.search(r'\\begin\{([^}]+)\}(.*?)\\end\{[^}]+\}', latex, re.DOTALL)
    if not env_match:
        raise ValueError("No matrix environment found in LaTeX")
    inner = env_match.group(2)
    row_strs = re.split(r'\\\\(?:\[[^\]]*\])?', inner)
    return [[cell.strip() for cell in r.split('&')] for r in row_strs if r.strip()]


def _column_content_glyph_indices(tex) -> list[int]:
    """Ordered glyph indices of a bmatrix column vector's *content*, brackets
    removed. Unlike get_matrix_grid_indices this keeps parentheses (which trip
    that function's h/w bracket test): the bmatrix brackets span every row so
    they are far taller than any in-entry glyph, and we split on height instead.
    Render order already runs entry-by-entry, top to bottom and left to right,
    so the returned list is in reading order.
    """
    glyphs = tex[0]
    max_h = max(g.height for g in glyphs)
    # Real matrix brackets are ~n_rows tall; the tallest content glyph (a paren)
    # is ~1 line, so 0.7*max_h sits comfortably between them for n_rows >= 2.
    return [i for i, g in enumerate(glyphs) if g.height <= 0.7 * max_h]


def animate_matrix_vector_product(matrix_tex, vector_tex, buff=0.6, place=None,
                                  **glyph_map_kwargs):
    """Animate `matrix_tex @ vector_tex` into an expanded product column vector.

    Builds a column vector whose i-th entry is the un-summed dot product
    ``(M_i0)(v_0) + (M_i1)(v_1) + ...`` using the *exact* source strings from the
    two inputs, and returns a TransformByGlyphMap that leaves `matrix_tex` and
    `vector_tex` in place while copies of each element fly into the result:
    every matrix element is used once, every vector element once per row.

    Inputs are the two on-screen MathTex objects (each a single bmatrix, with or
    without a "X = " style prefix), or MathTexPart slices of them.

    Positioning: the copies fly to wherever the result sits when the animation is
    *built*, so it must be placed up front. By default it goes to the right of
    `vector_tex` with `buff` spacing. Pass `place`, a callable taking the freshly
    built result MathTex, to put it anywhere instead, e.g.
    ``place=lambda r: r.next_to(eq_sign, RIGHT)`` or ``place=lambda r: r.move_to(pt)``.
    Grab the result afterwards via the returned animation's `.mobB`.
    """
    # 1. Source glyph indices (one re-render each) and shapes.
    grid_M = get_matrix_grid_indices(matrix_tex)
    grid_v = get_matrix_grid_indices(vector_tex)
    n, k = len(grid_M), len(grid_M[0])
    if len(grid_v) != k or len(grid_v[0]) != 1:
        raise ValueError(
            f"shape mismatch: matrix is {n}x{k} so vector must be {k}x1, "
            f"but got {len(grid_v)}x{len(grid_v[0])}"
        )

    # 2. Source strings, reused verbatim so glyph counts carry over.
    M_str = _matrix_entry_strings(matrix_tex)
    v_str = [row[0] for row in _matrix_entry_strings(vector_tex)]

    # 3. Build the expanded product vector, positioned at its final spot (the
    #    TransformByGlyphMap reads target positions now, so it must be placed).
    entries = [
        " + ".join(f"({M_str[i][j]})({v_str[j]})" for j in range(k))
        for i in range(n)
    ]
    result_tex = MathTex(r"\begin{bmatrix}" + r" \\ ".join(entries) + r"\end{bmatrix}")
    if place is not None:
        place(result_tex)
    else:
        result_tex.next_to(vector_tex, RIGHT, buff=buff)

    # 4. Walk the result's content glyphs in reading order, slicing out the
    #    target range of each copied factor by its known glyph count. Structural
    #    glyphs -- '(' ')' '+' -- are one glyph each and are skipped over.
    content = _column_content_glyph_indices(result_tex)
    pos = 0

    def take(count):
        nonlocal pos
        idxs = content[pos:pos + count]
        pos += count
        return idxs

    m_targets = [[None] * k for _ in range(n)]  # result glyphs for each matrix element copy
    v_targets = [[None] * k for _ in range(n)]  # result glyphs for each vector element copy
    for i in range(n):
        for j in range(k):
            if j > 0:
                take(1)                              # '+'
            take(1)                                  # '('
            m_targets[i][j] = take(len(grid_M[i][j]))
            take(1)                                  # ')'
            take(1)                                  # '('
            v_targets[i][j] = take(len(grid_v[j][0]))
            take(1)                                  # ')'
    if pos != len(content):
        raise RuntimeError(
            f"result glyph slicing mismatch: consumed {pos} of {len(content)} "
            f"content glyphs -- the built product vector isn't shaped as expected"
        )

    # 5. Wire copies: matrix element (i,j) -> its slot in row i; vector element j
    #    -> its slot in every row. from_copy keeps the originals untouched, and
    #    TransformByGlyphMap auto-copies any source index reused across rows.
    # Flatten both inputs' glyphs into one container (matrix first, then vector)
    # so a single index space addresses source[0]; works for full MathTex or a
    # MathTexPart slice, unlike CombineTex which assumes a full MathTex.
    source = VGroup(VGroup(*_tex_glyphs(matrix_tex), *_tex_glyphs(vector_tex)))
    len_M = len(_tex_glyphs(matrix_tex))
    glyph_map = []
    for i in range(n):
        for j in range(k):
            glyph_map.append((grid_M[i][j], m_targets[i][j]))
            glyph_map.append(([len_M + p for p in grid_v[j][0]], v_targets[i][j]))

    return TransformByGlyphMap(
        source, result_tex, *glyph_map,
        from_copy=True, auto_fade=True,
        **glyph_map_kwargs,
    )
