[project]
name = "hatmatrix"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "manim>=0.20.1",
    "manim-voiceover>=0.4.0",
    "stitch-tools",
]

[tool.uv.sources]
stitch-tools = { path = "../stitch-tools", editable = true }
